name: "PROD DEPLOYMENT"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'stage'
        run: |
          echo "ERROR: You can only merge to main from Stage."
          exit 1

  terraform:
    needs: validate-branch
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "prod"
      aws-assume-role-arn: "arn:aws:iam::730335498054:role/github-actions-rodrigochavesbr-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "rodrigochavesbr-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "rodrigochavesbr-sa-east-1-terraform-lock"
