name: "PROD DEPLOYMENT"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the push is from 'stage'
        run: |
          # Ensure the push event is valid
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "ERROR: This workflow is triggered only for pushes to the 'main' branch."
            exit 1
          fi

          # Check if the push is coming from the 'stage' branch
          base_branch=$(git for-each-ref --format '%(upstream:short)' $(git symbolic-ref -q HEAD) || echo "none")

          if [ "$base_branch" != "stage" ]; then
            echo "ERROR: You can only merge to 'main' from 'stage'."
            exit 1
          fi

  terraform:
    needs: check_branch
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "prod"
      aws-assume-role-arn: "arn:aws:iam::730335498054:role/github-actions-rodrigochavesbr-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "rodrigochavesbr-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "rodrigochavesbr-sa-east-1-terraform-lock"
