name: "STAGE DEPLOYMENT"
on:
  pull_request:
    branches:
      - stage

permissions:
  id-token: write
  contents: read

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from development branch
        id: check_pr_branch
        run: |
          if [[ "${{ github.head_ref }}" != "development" ]]; then
            echo "PR is not from the development branch"
            exit 1
          fi

      - name: Approve if from development branch
        if: success()
        run: echo "PR is from development branch, proceeding..."

  terraform:
    needs: check-branch
    if: needs.check-branch.result == 'success'
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "stage"
      aws-assume-role-arn: "arn:aws:iam::730335498054:role/github-actions-rodrigochavesbr-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "rodrigochavesbr-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "rodrigochavesbr-sa-east-1-terraform-lock"
